on:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VITE_API_URL: ${{ secrets.VITE_API_URL }}

jobs:
  Vercel-Deploy :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          echo "VITE_API_URL=$VITE_API_URL" > .env

      - name: Vercel pull (prod)
        run: npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Clean old output
        run: rm -rf .vercel/output || true

      - name: Vercel build (prod)
        run: npx vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy to Vercel (prod)
        run: npx vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN